# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import server_pb2 as proto_dot_server__pb2


class TodoServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateList = channel.unary_unary(
                '/TodoServer/CreateList',
                request_serializer=proto_dot_server__pb2.CreateListRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.Empty.FromString,
                )
        self.AddToList = channel.unary_unary(
                '/TodoServer/AddToList',
                request_serializer=proto_dot_server__pb2.AddToListRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.Item.FromString,
                )
        self.UpdateItemStatus = channel.unary_unary(
                '/TodoServer/UpdateItemStatus',
                request_serializer=proto_dot_server__pb2.UpdateItemStatusRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.Item.FromString,
                )
        self.GetLists = channel.unary_unary(
                '/TodoServer/GetLists',
                request_serializer=proto_dot_server__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_server__pb2.GetListsResponse.FromString,
                )
        self.GetList = channel.unary_unary(
                '/TodoServer/GetList',
                request_serializer=proto_dot_server__pb2.GetListRequest.SerializeToString,
                response_deserializer=proto_dot_server__pb2.GetListResponse.FromString,
                )


class TodoServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateList(self, request, context):
        """Creates a new todo list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToList(self, request, context):
        """Add a task to the list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemStatus(self, request, context):
        """Update a task's status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLists(self, request, context):
        """Gets all the created todo list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetList(self, request, context):
        """Gets a single list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateList': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateList,
                    request_deserializer=proto_dot_server__pb2.CreateListRequest.FromString,
                    response_serializer=proto_dot_server__pb2.Empty.SerializeToString,
            ),
            'AddToList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToList,
                    request_deserializer=proto_dot_server__pb2.AddToListRequest.FromString,
                    response_serializer=proto_dot_server__pb2.Item.SerializeToString,
            ),
            'UpdateItemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemStatus,
                    request_deserializer=proto_dot_server__pb2.UpdateItemStatusRequest.FromString,
                    response_serializer=proto_dot_server__pb2.Item.SerializeToString,
            ),
            'GetLists': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLists,
                    request_deserializer=proto_dot_server__pb2.Empty.FromString,
                    response_serializer=proto_dot_server__pb2.GetListsResponse.SerializeToString,
            ),
            'GetList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=proto_dot_server__pb2.GetListRequest.FromString,
                    response_serializer=proto_dot_server__pb2.GetListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TodoServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoServer/CreateList',
            proto_dot_server__pb2.CreateListRequest.SerializeToString,
            proto_dot_server__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoServer/AddToList',
            proto_dot_server__pb2.AddToListRequest.SerializeToString,
            proto_dot_server__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoServer/UpdateItemStatus',
            proto_dot_server__pb2.UpdateItemStatusRequest.SerializeToString,
            proto_dot_server__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoServer/GetLists',
            proto_dot_server__pb2.Empty.SerializeToString,
            proto_dot_server__pb2.GetListsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TodoServer/GetList',
            proto_dot_server__pb2.GetListRequest.SerializeToString,
            proto_dot_server__pb2.GetListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
